/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package ripl;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class heartbeat_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long tol_utime;
    public int state;
    public String comment;
 
    public heartbeat_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x942b1f9fee1c1b8bL;
 
    public static final int STATE_UNKNOWN = 0;
    public static final int STATE_ALL_OK = 1;
    public static final int STATE_INIT = 2;
    public static final int STATE_WARN = 3;
    public static final int STATE_ERROR = 4;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(ripl.heartbeat_t.class))
            return 0L;
 
        classes.add(ripl.heartbeat_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.tol_utime); 
 
        outs.writeInt(this.state); 
 
        __strbuf = new char[this.comment.length()]; this.comment.getChars(0, this.comment.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public heartbeat_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public heartbeat_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static ripl.heartbeat_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        ripl.heartbeat_t o = new ripl.heartbeat_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.tol_utime = ins.readLong();
 
        this.state = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.comment = new String(__strbuf);
 
    }
 
    public ripl.heartbeat_t copy()
    {
        ripl.heartbeat_t outobj = new ripl.heartbeat_t();
        outobj.utime = this.utime;
 
        outobj.tol_utime = this.tol_utime;
 
        outobj.state = this.state;
 
        outobj.comment = this.comment;
 
        return outobj;
    }
 
}

