/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package ripl;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_state_command_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte state;
    public long faults;
    public long fault_mask;
    public String sender;
    public String comment;
 
    public robot_state_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6f45f48f76875ac1L;
 
    public static final byte STATE_UNDEFINED = (byte) 0;
    public static final byte STATE_RUN = (byte) 1;
    public static final byte STATE_STANDBY = (byte) 2;
    public static final byte STATE_STOP = (byte) 3;
    public static final byte STATE_MANUAL = (byte) 4;
    public static final byte STATE_ERROR = (byte) 5;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(ripl.robot_state_command_t.class))
            return 0L;
 
        classes.add(ripl.robot_state_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.state); 
 
        outs.writeLong(this.faults); 
 
        outs.writeLong(this.fault_mask); 
 
        __strbuf = new char[this.sender.length()]; this.sender.getChars(0, this.sender.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.comment.length()]; this.comment.getChars(0, this.comment.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public robot_state_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_state_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static ripl.robot_state_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        ripl.robot_state_command_t o = new ripl.robot_state_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.state = ins.readByte();
 
        this.faults = ins.readLong();
 
        this.fault_mask = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.sender = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.comment = new String(__strbuf);
 
    }
 
    public ripl.robot_state_command_t copy()
    {
        ripl.robot_state_command_t outobj = new ripl.robot_state_command_t();
        outobj.utime = this.utime;
 
        outobj.state = this.state;
 
        outobj.faults = this.faults;
 
        outobj.fault_mask = this.fault_mask;
 
        outobj.sender = this.sender;
 
        outobj.comment = this.comment;
 
        return outobj;
    }
 
}

