"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class heartbeat_t(object):
    __slots__ = ["utime", "tol_utime", "state", "comment"]

    __typenames__ = ["int64_t", "int64_t", "int32_t", "string"]

    __dimensions__ = [None, None, None, None]

    STATE_UNKNOWN = 0
    STATE_ALL_OK = 1
    STATE_INIT = 2
    STATE_WARN = 3
    STATE_ERROR = 4

    def __init__(self):
        self.utime = 0
        self.tol_utime = 0
        self.state = 0
        self.comment = ""

    def encode(self):
        buf = BytesIO()
        buf.write(heartbeat_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqi", self.utime, self.tol_utime, self.state))
        __comment_encoded = self.comment.encode('utf-8')
        buf.write(struct.pack('>I', len(__comment_encoded)+1))
        buf.write(__comment_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != heartbeat_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return heartbeat_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = heartbeat_t()
        self.utime, self.tol_utime, self.state = struct.unpack(">qqi", buf.read(20))
        __comment_len = struct.unpack('>I', buf.read(4))[0]
        self.comment = buf.read(__comment_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if heartbeat_t in parents: return 0
        tmphash = (0x942b1f9fee1c1b8b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if heartbeat_t._packed_fingerprint is None:
            heartbeat_t._packed_fingerprint = struct.pack(">Q", heartbeat_t._get_hash_recursive([]))
        return heartbeat_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

