"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_state_command_t(object):
    __slots__ = ["utime", "state", "faults", "fault_mask", "sender", "comment"]

    __typenames__ = ["int64_t", "int8_t", "int64_t", "int64_t", "string", "string"]

    __dimensions__ = [None, None, None, None, None, None]

    STATE_UNDEFINED = 0
    STATE_RUN = 1
    STATE_STANDBY = 2
    STATE_STOP = 3
    STATE_MANUAL = 4
    STATE_ERROR = 5

    def __init__(self):
        self.utime = 0
        self.state = 0
        self.faults = 0
        self.fault_mask = 0
        self.sender = ""
        self.comment = ""

    def encode(self):
        buf = BytesIO()
        buf.write(robot_state_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbqq", self.utime, self.state, self.faults, self.fault_mask))
        __sender_encoded = self.sender.encode('utf-8')
        buf.write(struct.pack('>I', len(__sender_encoded)+1))
        buf.write(__sender_encoded)
        buf.write(b"\0")
        __comment_encoded = self.comment.encode('utf-8')
        buf.write(struct.pack('>I', len(__comment_encoded)+1))
        buf.write(__comment_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_state_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_state_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_state_command_t()
        self.utime, self.state, self.faults, self.fault_mask = struct.unpack(">qbqq", buf.read(25))
        __sender_len = struct.unpack('>I', buf.read(4))[0]
        self.sender = buf.read(__sender_len)[:-1].decode('utf-8', 'replace')
        __comment_len = struct.unpack('>I', buf.read(4))[0]
        self.comment = buf.read(__comment_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_state_command_t in parents: return 0
        tmphash = (0x6f45f48f76875ac1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_state_command_t._packed_fingerprint is None:
            robot_state_command_t._packed_fingerprint = struct.pack(">Q", robot_state_command_t._get_hash_recursive([]))
        return robot_state_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

